### ISSUE TITLE
UnsupportedOperationException when autofishing

### ISSUE THREAD

**Issue by AlekseyVideman** [ploppyperson/RealFish#4]
Log:
```
[15:18:01 ERROR]: Could not pass event PlayerFishEvent to RealFish v1.1.0-SNAPSHOT
java.lang.UnsupportedOperationException: Normal fishing is still occurring!
        at RealFish-1.1.0-SNAPSHOT.jar/uk.antiperson.realfish.Listeners.onFish(Listeners.java:44) ~[RealFish-1.1.0-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor864.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2260-5e70800]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2260-5e70800]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2260-5e70800]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.projectile.FishingHook.retrieve(FishingHook.java:543) ~[purpur-1.21.jar:1.21-2260-5e70800]
        at net.minecraft.world.item.FishingRodItem.use(FishingRodItem.java:33) ~[purpur-1.21.jar:1.21-2260-5e70800]
        at net.minecraft.world.item.ItemStack.use(ItemStack.java:605) ~[purpur-1.21.jar:1.21-2260-5e70800]
        at net.minecraft.server.level.ServerPlayerGameMode.useItem(ServerPlayerGameMode.java:489) ~[purpur-1.21.jar:1.21-2260-5e70800]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2040) ~[purpur-1.21.jar:1.21-2260-5e70800]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:47) ~[purpur-1.21.jar:1.21-2260-5e70800]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:10) ~[purpur-1.21.jar:1.21-2260-5e70800]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.jar:1.21-2260-5e70800]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2260-5e70800]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2260-5e70800]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2260-5e70800]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1577) ~[purpur-1.21.jar:1.21-2260-5e70800]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2260-5e70800]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2260-5e70800]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1554) ~[purpur-1.21.jar:1.21-2260-5e70800]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1547) ~[purpur-1.21.jar:1.21-2260-5e70800]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2260-5e70800]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1506) ~[purpur-1.21.jar:1.21-2260-5e70800]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1513) ~[purpur-1.21.jar:1.21-2260-5e70800]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1358) ~[purpur-1.21.jar:1.21-2260-5e70800]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2260-5e70800]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

How to reproduce:
1. Take a fishing rod.
2. Start to fish using autoclicker.

**Comment by ploppyperson** [comment]
Which autoclicker are you using?

**Comment by AlekseyVideman** [comment]
> Which autoclicker are you using?

https://modrinth.com/mod/auto-clicker
